# 该配置不能替代 requirements.txt，该配置不指定依赖，该配置只是为了统一配置格式化工具存在的

[project]
name = "Qbot"
version = "0.9.8"
description = "快速部署具有极强AI自控自由度的大语言模型AI-QQ机器人，自带联网，AI驱动的提示词切换，AI驱动的中期记忆，长期记忆能力，AI自主分段回复，可附加包含语音，绘画，全曲库翻唱等功能。"
authors = [
  { name = "TIGillusion" },
  { name = "GaoYuan522" }
  ]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.8"

[tool.isort]
profile = "black"
line_length = 127

[tool.black]
line-length = 127
skip-string-normalization = true