name: Test-and-build

on:
  push:
  pull_request:

jobs:
  windows-build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.14"]

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 Isort black pyinstaller 
        # pytest
        if ( Test-Path requirements.txt ) { pip install -r requirements.txt }
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --statistics
    #- name: Test with pytest
      #run: |
        #if ( false ) { pytest }
    - name: Build the binary
      run: |
        pyinstaller --onefile Qbot.py
      env:
        CI: false
    - name: Upload the binary
      uses: actions/upload-artifact@v7
      with:
        name: ${{ format('Qbot-{0}-Python{1}.exe', runner.os, matrix.python-version) }}
        path: dist/Qbot.exe
    - name: Upload the code
      uses: actions/upload-artifact@v7
      with:
        name: ${{ format('Qbot-{0}-Python{1}.py', runner.os, matrix.python-version) }}
        path: Qbot.py
    - name: Isort the code
      run: |
        isort . --check --diff
        isort .
      env:
        PYTHONUTF8: 1
    - name: Black the code
      run: |
        black . --check --diff
        black .
    - name: Lint formatted code with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --statistics
    - name: Upload the formatted code
      uses: actions/upload-artifact@v7
      with:
        name: ${{ format('Qbot-{0}-Python{1}-Isort-Black.py', runner.os, matrix.python-version) }}
        path: Qbot.py
    - name: Build the binary with the formatted code
      run: |
        pyinstaller --onefile Qbot.py
      env:
        CI: false
    - name: Upload the binary with the formatted code
      uses: actions/upload-artifact@v7
      with:
        name: ${{ format('Qbot-{0}-Python{1}-Isort-Black.exe', runner.os, matrix.python-version) }}
        path: dist/Qbot.exe
